mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  username: slimeworldmanager
  password: ''
  database: slimeworldmanager
  usessl: false
mongodb:
  enabled: false
  host: 127.0.0.1
  port: 27017
  auth: admin
  username: slimeworldmanager
  password: ''
  database: slimeworldmanager
  collection: worlds
  uri: ''
file:
  path: slime_worlds